### ISSUE TITLE
docker image does not include TLS certificate files required for s3 over TLS to work.

### ISSUE THREAD

**Issue by apesternikov** [buildbarn/bb-storage#19]

**Comment by apesternikov** [comment]
```java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=@six//:rename BuildConfigurationValue.Key[639184f3229c20b13e610f025ec7662e] true, actionIndex=0}' (requested by nodes 'File:[[<execution_root>]bazel-out/host/bin]external/six/__init__.py')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:528)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:399)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: io.grpc.StatusRuntimeException: UNKNOWN: blob (code=Unknown): RequestError: send request failed
caused by: Head https://s3.us-east-1.amazonaws.com/my-bucket-is-here/bazel_cas/ccac5608a8dee46a6bd3a20858d8102fcfbc189f6bc00ba51340e75812b39a11-29664: x509: certificate signed by unknown authority
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.getMissingDigests(GrpcRemoteCache.java:206)
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.upload(GrpcRemoteCache.java:432)
	at com.google.devtools.build.lib.remote.GrpcRemoteCache.upload(GrpcRemoteCache.java:389)
	at com.google.devtools.build.lib.remote.RemoteSpawnCache$1.store(RemoteSpawnCache.java:245)
	at com.google.devtools.build.lib.exec.AbstractSpawnStrategy.exec(AbstractSpawnStrategy.java:125)
...
```

**Comment by apesternikov** [comment]
using 
`load("@io_bazel_rules_docker//go:image.bzl", "go_image")` instead of container_image fixes the issue.

**Comment by mickael-carl** [comment]
Thanks for reporting! You can use the `buildbarn/bb-storage:20190802T155201Z-9fe17c4` or later, docker image, it should have the CA certificates.
